image: node:8

services:
    - dcr.buyme360.com/devops/docker:dind

variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    IMAGE_TAG2: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
    NODE_ENV: production
    DOCKER_HOST: tcp://localhost:2375

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
    key: $CI_JOB_NAME
    paths:
        - node_modules/

build:
    stage: build
    script:
        - npm i -g webpack@2.6.1
        - NODE_ENV=development npm i
        - webpack

# TODO: Run unit tests as part of the check stage
