image: node:8

services:
    - dcr.buyme360.com/devops/docker:dind

stages:
- build
- package
- deploy

variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
    IMAGE_TAG_ARM: $CI_REGISTRY_IMAGE/arm:$CI_COMMIT_REF_SLUG
    NODE_ENV: production
    DOCKER_HOST: tcp://localhost:2375

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
    key: $CI_JOB_NAME
    paths:
        - node_modules/

build:
    stage: build
    script:
        - NODE_ENV=development npm i
        - npm i -g gulp-cli
        - gulp
    artifacts:
      paths:
        - dist/

package:
    stage: package
    image: dcr.buyme360.com/devops/docker:latest
    script:
        - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
        # get the current image for better performance
        - docker pull $IMAGE_TAG
        - docker build -t $IMAGE_TAG .
        - docker build -t $IMAGE_TAG_ARM -f Dockerfile.arm .
        - docker push $IMAGE_TAG
        - docker push $IMAGE_TAG_ARM
    dependencies:
        - build

auto_mirror:
  image: alpine/git:latest
  stage: deploy
  script:
    - if [ ! -z "$GITHUB_EXPLORER_PUSH_KEY" ]; then
    -   mkdir /root/.ssh
    -   echo "$GITHUB_EXPLORER_PUSH_KEY" > /root/.ssh/id_rsa
    -   chmod 400 /root/.ssh/id_rsa
    # we have to include this in order for github's server to be verified
    -   echo "github.com,192.30.252.130 ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==" > /root/.ssh/known_hosts
    -   git push git@github.com:blockscape/blockscape-explorer.git HEAD:$CI_COMMIT_REF_NAME
    -   git push --tags git@github.com:blockscape/blockscape-explorer.git HEAD:$CI_COMMIT_REF_NAME
    - fi

# TODO: Run unit tests as part of the check stage
