image: node:8

services:
    - dcr.buyme360.com/devops/docker:dind

stages:
- build
- package

variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
    NODE_ENV: production
    DOCKER_HOST: tcp://localhost:2375

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
    key: $CI_JOB_NAME
    paths:
        - node_modules/

build:
    stage: build
    script:
        - NODE_ENV=development npm i
        - npm i -g gulp-cli webpack
        - gulp
    artifacts:
      paths:
        - dist/

package:
    stage: package
    image: dcr.buyme360.com/devops/docker:latest
    script:
        - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
        - docker build -t $IMAGE_TAG .
        - docker push $IMAGE_TAG
    dependencies:
        - build

# TODO: Run unit tests as part of the check stage
