FROM arm32v6/node:10-alpine

EXPOSE 3000

WORKDIR /usr/src

CMD ["/bin/ash", "-c", "npm i -g ts-node typescript && npm i -production && ts-node lib/server.ts"]

STOPSIGNAL SIGINT

COPY package.json package-lock.json tsconfig.json dist/ /usr/src/
